/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Junjie_Li
 */
import java.util.ArrayList;
import javax.swing.DefaultListModel; 

class A { 
    int x; 
    int y; 
    public A(int x, int y){ 
        this.x=x; 
        this.y=y; 
    } 
    @Override 
    public String toString(){ 
        return "x= " + x +"\ny= " + y; 
    } 
}
    

public class Demo extends javax.swing.JFrame {
    
        ArrayList<A> llista = null;
    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        chkBotonsActius.setSelected(true); 
        txtMissatge.setEnabled(true); 
        afegirDadesTest();
        btnEliminar.setEnabled(false);
    }
    
    private void afegirDadesTest(){
        llista = new ArrayList<A>(); 
        llista.add(new A(1,2)); 
        llista.add(new A(3,4)); 
        llista.add(new A(5,6)); 
    }

    

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMissatge = new javax.swing.JTextField();
        btnHola = new javax.swing.JButton();
        btnAdeu = new javax.swing.JButton();
        chkBotonsActius = new javax.swing.JCheckBox();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLlista1 = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMissatge.setBackground(new java.awt.Color(255, 255, 0));
        txtMissatge.setColumns(1);
        txtMissatge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMissatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMissatgeActionPerformed(evt);
            }
        });

        btnHola.setText("HOLA");
        btnHola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHolaActionPerformed(evt);
            }
        });

        btnAdeu.setText("ADEU");
        btnAdeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdeuActionPerformed(evt);
            }
        });

        chkBotonsActius.setText("Botons Actius ");
        chkBotonsActius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBotonsActiusStateChanged(evt);
            }
        });
        chkBotonsActius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBotonsActiusActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar Llista");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lstLlista1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLlista1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLlista1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstLlista1);

        btnEliminar.setText(" Eliminar ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMissatge, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHola)
                                .addGap(49, 49, 49)
                                .addComponent(btnAdeu)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBotonsActius)
                            .addComponent(btnMostrar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtMissatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHola)
                    .addComponent(btnAdeu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(chkBotonsActius)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMostrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnEliminar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHolaActionPerformed
        // TODO add your handling code here:
        txtMissatge.setText(btnHola.getText()); 
    }//GEN-LAST:event_btnHolaActionPerformed

    private void txtMissatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMissatgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMissatgeActionPerformed

    private void btnAdeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdeuActionPerformed
        // TODO add your handling code here:
        txtMissatge.setText(btnAdeu.getText()); 
    }//GEN-LAST:event_btnAdeuActionPerformed

    private void chkBotonsActiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBotonsActiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBotonsActiusActionPerformed

    private void chkBotonsActiusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBotonsActiusStateChanged
        // TODO add your handling code here:
        btnHola.setEnabled(chkBotonsActius.isSelected()); 
        btnAdeu.setEnabled(chkBotonsActius.isSelected()); 
    }//GEN-LAST:event_chkBotonsActiusStateChanged

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        omplirLlista();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        for(Object item: lstLlista1.getSelectedValuesList()){
            A elementSeleccionat = (A) item; 
            llista.remove(elementSeleccionat); 
        } 
        omplirLlista();  
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void lstLlista1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLlista1ValueChanged
        // TODO add your handling code here:
        btnEliminar.setEnabled(!lstLlista1.isSelectionEmpty()); 
    }//GEN-LAST:event_lstLlista1ValueChanged
    void omplirLlista(){ 
        DefaultListModel model = new DefaultListModel();        
        model.clear(); 
        for(A item: llista){
            model.addElement(item);
        } 
        lstLlista1.setModel(model); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdeu;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHola;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox chkBotonsActius;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstLlista1;
    private javax.swing.JTextField txtMissatge;
    // End of variables declaration//GEN-END:variables
}
