/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linzhihanlijunjie_l4.vista;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import linzhihanlijunjie_l4.controlador.Controlador;
/**
 *
 * @author Zhihan_Lin i Junjie_Li
 */

public class FrmAfegirArticle extends javax.swing.JDialog {

    /**
     * Creates new form FrmAfegirArticle
     */
    private Controlador controlador;
    private java.awt.Frame parent;
    public FrmAfegirArticle(java.awt.Frame parent, boolean modal,Controlador controlador) {
        super(parent, modal);
        ImageIcon icon =new ImageIcon("images\\Icono.png");
        this.setIconImage(icon.getImage());
        this.controlador = controlador;
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_DadesArticle = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();
        label_Identificador = new javax.swing.JLabel();
        label_Preu = new javax.swing.JLabel();
        label_tempsFinsEnviament = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JTextField();
        txtTempsFinsEnviament = new javax.swing.JTextField();
        txtPreu = new javax.swing.JTextField();
        ckBoxAdmetEnviamentUrgent = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnAcceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 540));
        setSize(new java.awt.Dimension(700, 540));

        label_DadesArticle.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_DadesArticle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_DadesArticle.setText("Dades d'Article");
        label_DadesArticle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_nom.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        label_nom.setText("Nom:");

        label_Identificador.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        label_Identificador.setText("Identificador:");

        label_Preu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        label_Preu.setText("Preu:");

        label_tempsFinsEnviament.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        label_tempsFinsEnviament.setText("Temps fins l'enviament: ");

        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });

        txtIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentificadorKeyPressed(evt);
            }
        });

        txtTempsFinsEnviament.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTempsFinsEnviamentKeyPressed(evt);
            }
        });

        txtPreu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPreuKeyPressed(evt);
            }
        });

        ckBoxAdmetEnviamentUrgent.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ckBoxAdmetEnviamentUrgent.setText("Admet Enviament urgent");
        ckBoxAdmetEnviamentUrgent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ckBoxAdmetEnviamentUrgentKeyPressed(evt);
            }
        });

        btnCancel.setText("Cancel·lar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAcceptar.setText("Acceptar");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_DadesArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBoxAdmetEnviamentUrgent)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_tempsFinsEnviament)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTempsFinsEnviament, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Preu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreu, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_DadesArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Preu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tempsFinsEnviament, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempsFinsEnviament, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckBoxAdmetEnviamentUrgent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Mètode que accepta afegir un article quan pulsem el butó acceptar
     * @param evt ActionEvent
     */
    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        String id = txtIdentificador.getText();
        String nom = txtNom.getText();
        boolean admetUrgent = ckBoxAdmetEnviamentUrgent.isSelected();
        
        if(id.equals("") || nom.equals("") || txtTempsFinsEnviament.getText().equals("") || txtPreu.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"No pots deixar en blanc algun apartat!","Error",JOptionPane.ERROR_MESSAGE);
        }else{        
            try {
                float preu = Float.parseFloat(txtPreu.getText());
                int tempsFinsEnviament = Integer.parseInt(txtTempsFinsEnviament.getText());
                controlador.AfegirArticle(id,nom,preu,tempsFinsEnviament,admetUrgent);
                FrmGestioArticles frmGestioArticles = (FrmGestioArticles) parent;
                frmGestioArticles.omplirLlistaArticles();
                this.dispose();
            }catch (MercatException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }catch (Exception ex)  {
                JOptionPane.showMessageDialog(this,"No pots posar lletres en lloc de preu/temps!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAcceptarActionPerformed
    /**
     * mètode que sortir de la finestra quan pulsem el butó cancel·lar
     * @param evt 
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
/**
 * Mètode que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void txtIdentificadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificadorKeyPressed
        PressKeyToClickButton(evt);
    }//GEN-LAST:event_txtIdentificadorKeyPressed

    /**
 * Mètode que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        PressKeyToClickButton(evt);
    }//GEN-LAST:event_txtNomKeyPressed

/**
 * Mètode que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void txtPreuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreuKeyPressed
        PressKeyToClickButton(evt);
    }//GEN-LAST:event_txtPreuKeyPressed

/**
 * Mètode que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void txtTempsFinsEnviamentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempsFinsEnviamentKeyPressed
        PressKeyToClickButton(evt);
    }//GEN-LAST:event_txtTempsFinsEnviamentKeyPressed

/**
 * Mètode que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void ckBoxAdmetEnviamentUrgentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ckBoxAdmetEnviamentUrgentKeyPressed
        PressKeyToClickButton(evt);
    }//GEN-LAST:event_ckBoxAdmetEnviamentUrgentKeyPressed

/**
 * Mètode de suport que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */
    private void PressKeyToClickButton(java.awt.event.KeyEvent evt){
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnAcceptar.doClick();
        }else if(evt.getKeyChar() == KeyEvent.VK_ESCAPE){
            btnCancel.doClick();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JCheckBox ckBoxAdmetEnviamentUrgent;
    private javax.swing.JLabel label_DadesArticle;
    private javax.swing.JLabel label_Identificador;
    private javax.swing.JLabel label_Preu;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_tempsFinsEnviament;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPreu;
    private javax.swing.JTextField txtTempsFinsEnviament;
    // End of variables declaration//GEN-END:variables
}
