/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linzhihanlijunjie_l4.vista;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import linzhihanlijunjie_l4.controlador.Controlador;

/**
 *
 *  @author Zhihan_Lin i Junjie_Li
 */
public class FrmGestioComandes extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestioComandes
     */
    private Controlador controlador;
    public FrmGestioComandes(Controlador controlador) {
        ImageIcon icon =new ImageIcon("images\\Icono.png");
        this.setIconImage(icon.getImage());
        initComponents();
        this.controlador = controlador;
        jButton_EliminarComanda.setEnabled(false);
        omplirLlistaComandes();
        this.setDefaultCloseOperation(0);  
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_GestioComandes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_VisualitzaComandes = new javax.swing.JList<>();
        jLabel_GestioComandes = new javax.swing.JLabel();
        jCheckBox_LlistaComandesUrgents = new javax.swing.JCheckBox();
        jButton_AfegirComanda = new javax.swing.JButton();
        jButton_EliminarComanda = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 540));
        setSize(new java.awt.Dimension(700, 540));

        jPanel_GestioComandes.setPreferredSize(new java.awt.Dimension(700, 540));

        jList_VisualitzaComandes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_VisualitzaComandesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_VisualitzaComandes);

        jLabel_GestioComandes.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel_GestioComandes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_GestioComandes.setText("Gestió Comandes");

        jCheckBox_LlistaComandesUrgents.setText("Lista Comandes Urgents");
        jCheckBox_LlistaComandesUrgents.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_LlistaComandesUrgentsStateChanged(evt);
            }
        });

        jButton_AfegirComanda.setText("Afegir Comanda");
        jButton_AfegirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AfegirComandaActionPerformed(evt);
            }
        });

        jButton_EliminarComanda.setText("Eliminar Comanda");
        jButton_EliminarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarComandaActionPerformed(evt);
            }
        });

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_GestioComandesLayout = new javax.swing.GroupLayout(jPanel_GestioComandes);
        jPanel_GestioComandes.setLayout(jPanel_GestioComandesLayout);
        jPanel_GestioComandesLayout.setHorizontalGroup(
            jPanel_GestioComandesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GestioComandesLayout.createSequentialGroup()
                .addGroup(jPanel_GestioComandesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(jCheckBox_LlistaComandesUrgents, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton_AfegirComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_EliminarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel_GestioComandes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133)))
                .addGap(25, 25, 25))
        );
        jPanel_GestioComandesLayout.setVerticalGroup(
            jPanel_GestioComandesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GestioComandesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_GestioComandes, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_LlistaComandesUrgents, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addGroup(jPanel_GestioComandesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GestioComandesLayout.createSequentialGroup()
                        .addGroup(jPanel_GestioComandesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_EliminarComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jButton_AfegirComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_GestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_GestioComandes, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * mètode que surt del finestra quan cliquem el butó cancel·lar
 * @param evt ActionEvent
 */
    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_SalirActionPerformed
/**
 * mètode que elimina una comanda seleccionada quan pulsem el butó eliminar
 * @param evt ActionEvent
 */
    private void jButton_EliminarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarComandaActionPerformed

        try{
            if(LlistaComandesUrgentsisSelected()){
                omplirLlistaComandesUrgents();
            }else{
                omplirLlistaComandes();
            }
                        
            int pos = jList_VisualitzaComandes.getLeadSelectionIndex();
            controlador.EsborrarComanda(pos);
            
            if(LlistaComandesUrgentsisSelected()){
                omplirLlistaComandesUrgents();
            }else{
                omplirLlistaComandes();
            }
                        

        }catch(MercatException ex){
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_EliminarComandaActionPerformed
    /**
     * mètode que s'obre un JDialog per afegir un article quan pulsem el butó
     * @param evt ActionEvent
     */
    private void jButton_AfegirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AfegirComandaActionPerformed
        try {
            FrmAfegirComandes frmAfegirComandes = new FrmAfegirComandes(this, true, controlador);
            frmAfegirComandes.setTitle("Dades Article");
            frmAfegirComandes.omplirComboBoxArticles();
            frmAfegirComandes.omplirComboBoxClients();
            frmAfegirComandes.pack();
            frmAfegirComandes.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_AfegirComandaActionPerformed
/**
 * mètode que mostra la llista de comandes urgents o tota la llista segons que el checkBox estigui seliccionat o no
 * @param evt 
 */
    private void jCheckBox_LlistaComandesUrgentsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_LlistaComandesUrgentsStateChanged

        if(!jCheckBox_LlistaComandesUrgents.isSelected()){
            omplirLlistaComandes();
        }else{
            omplirLlistaComandesUrgents();
        }
    }//GEN-LAST:event_jCheckBox_LlistaComandesUrgentsStateChanged
/**
 * mètode que desactiva el butó eliminar quan no seleccionem cap comanda de la llista
 * @param evt ListSelectionEvent
 */
    private void jList_VisualitzaComandesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_VisualitzaComandesValueChanged
        jButton_EliminarComanda.setEnabled(!jList_VisualitzaComandes.isSelectionEmpty());
    }//GEN-LAST:event_jList_VisualitzaComandesValueChanged

 /**
 * Mètode de suport que actualitza la llista dels de totes les comandes
 */        
    void omplirLlistaComandes() {
        DefaultListModel model = new DefaultListModel();
        for(String s :controlador.recuperaComandes()){
            model.addElement(s);
        }
        this.jList_VisualitzaComandes.setModel(model);
    }
/**
 * Mètode de suport que actualitza la llista dels de les comandes urgents
 */ 
    void omplirLlistaComandesUrgents() {
        DefaultListModel model = new DefaultListModel();
        for(String s :controlador.recuperaComandesUrgents()){
            model.addElement(s);
        }
        this.jList_VisualitzaComandes.setModel(model);
    }
/**
 * Mètode de suport que retorna si el checkbox de tria si és la llista de totes les comanda o només urgent
 * @return retorna true si la llista de comandes urgent està seleccionada
 */    
    boolean LlistaComandesUrgentsisSelected(){
        return jCheckBox_LlistaComandesUrgents.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AfegirComanda;
    private javax.swing.JButton jButton_EliminarComanda;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JCheckBox jCheckBox_LlistaComandesUrgents;
    private javax.swing.JLabel jLabel_GestioComandes;
    private javax.swing.JList<String> jList_VisualitzaComandes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_GestioComandes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
