/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linzhihanlijunjie_l4.vista;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import linzhihanlijunjie_l4.controlador.Controlador;

/**
 *
 * @author Zhihan_Lin i Junjie_Li
 */
public class FrmGestioClients extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestioClients
     */
    Controlador controlador;
    public FrmGestioClients(Controlador controlador) {
        ImageIcon icon =new ImageIcon("images\\Icono.png");
        this.setIconImage(icon.getImage());
        initComponents();
        this.controlador = controlador;
        omplirLlistaClients();
        this.setDefaultCloseOperation(0);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        label_GestioClients = new javax.swing.JLabel();
        btn_AfegirClient = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_VisualitzarClient = new javax.swing.JList<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 540));
        setSize(new java.awt.Dimension(700, 540));

        label_GestioClients.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_GestioClients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_GestioClients.setText("Gestió Clients");

        btn_AfegirClient.setText("Afegir Client");
        btn_AfegirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AfegirClientActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList_VisualitzarClient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btn_AfegirClient, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(160, 160, 160)
                .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(label_GestioClients, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_GestioClients, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * mètode que s'obre un JDialog per afegir un article quan pulsem el butó
     * @param evt ActionEvent
     */
    private void btn_AfegirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AfegirClientActionPerformed
        FrmAfegirClient frmAfegirClient = new FrmAfegirClient(this,true,controlador);
        frmAfegirClient.setTitle("Dades Client"); 
        frmAfegirClient.pack(); 
        frmAfegirClient.setVisible(true); 
    }//GEN-LAST:event_btn_AfegirClientActionPerformed
/**
 * mètode que surt del finestra quan cliquem el butó cancel·lar
 * @param evt ActionEvent
 */
    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed
/**
 * Mètode de suport que quan pulsem el teclat es clicarà automàticament el butó
 * @param evt el teclat que pulsem
 */    
    void omplirLlistaClients() {
        DefaultListModel model = new DefaultListModel();
        for(String s :controlador.recuperaClients()){
            model.addElement(s);
        }
        this.jList_VisualitzarClient.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AfegirClient;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JList<String> jList_VisualitzarClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_GestioClients;
    // End of variables declaration//GEN-END:variables
}
